In [1]:
import numpy as np
from scipy.linalg import toeplitz

In [2]:
import warnings; warnings.simplefilter("always")

In [3]:
A=toeplitz([2,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
A

array([[ 2, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [-1,  2, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0, -1,  2, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0, -1,  2, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0, -1,  2, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  2, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  2, -1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  2, -1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1,  2, -1,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  2, -1,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0

In [4]:
A.shape

(20, 20)

In [5]:
def GramSchmidt(A):

    m = A.shape[1]
    Q = np.zeros(A.shape, dtype=np.double)
    temp_vector = np.zeros(m, dtype=np.double)

    Q[:, 0] = A[:, 0] / np.linalg.norm(A[:, 0], ord=2)

    for i in range(1, m):
        q = Q[:, :i]
        temp_vector = np.sum(np.sum(q * A[:, i, None], axis=0) * q, axis=1)
        Q[:, i] = A[:, i] - temp_vector
        Q[:, i] /= np.linalg.norm(Q[:, i], ord=2)

    return Q

In [6]:
def QRFactorization(A):

    Q = GramSchmidt(A)
    Q_T = Q.transpose()
    R = np.matmul(Q_T,A) #Q.T @ A

    return(Q, R)


 First matrix Q got from below code (QRFactorization(A)) actually consist of eigenvectors of our toeplitz matrix. These eigenvectors are perpendicular each other and their norm is 1.

In [7]:
QRFactorization(A)

(array([[ 0.89442719,  0.35856858,  0.19518001,  0.12309149,  0.08481042,
          0.06201737,  0.04733811,  0.03732545,  0.03018889,  0.02492224,
          0.02092422,  0.01781742,  0.01535511,  0.01337049,  0.01174744,
          0.01040313,  0.00927716,  0.00832467,  0.00751174,  0.01866633],
        [-0.4472136 ,  0.71713717,  0.39036003,  0.24618298,  0.16962084,
          0.12403473,  0.09467621,  0.07465089,  0.06037779,  0.04984448,
          0.04184844,  0.03563483,  0.03071023,  0.02674098,  0.02349489,
          0.02080626,  0.01855432,  0.01664933,  0.01502348,  0.03733267],
        [ 0.        , -0.5976143 ,  0.58554004,  0.36927447,  0.25443126,
          0.1860521 ,  0.14201432,  0.11197634,  0.09056668,  0.07476672,
          0.06277266,  0.05345225,  0.04606534,  0.04011148,  0.03524233,
          0.03120939,  0.02783148,  0.024974  ,  0.02253522,  0.055999  ],
        [ 0.        ,  0.        , -0.68313005,  0.49236596,  0.33924168,
          0.24806947,  0.18935243, 

**Unshifted QR Algorithm to find eigenvalues**

This unshifted QR algorithm gives us that the sequence  A0,A1,…,  have the same eigenvalues and for any large integer  k  the matrix  Ak  is usually close to being upper-triangular. 
Because of this iteration, we can approach the eigenvalues of A from the diagonal entries of Ak.
Since the eigenvalues of an upper-triangular matrix lie on its diagonal 

In [8]:
def unshifted_QR_eigval(A):
    for k in range(1,1000):
        (Q,R) =  QRFactorization(A) # compute the QR factorization of A
        A = np.matmul(R,Q)  # reverse the factors
    for i in range(20):
        print("Eigenvalue",i,":",A[i,i])
      

In [9]:
unshifted_QR_eigval(A)

Eigenvalue 0 : 3.9776616524502466
Eigenvalue 1 : 3.911145611572297
Eigenvalue 2 : 3.801937735804832
Eigenvalue 3 : 3.6524775486319903
Eigenvalue 4 : 3.466103743659648
Eigenvalue 5 : 3.2469796037174636
Eigenvalue 6 : 2.9999999999999765
Eigenvalue 7 : 2.730682048732798
Eigenvalue 8 : 2.4450418679126233
Eigenvalue 9 : 2.1494601871728483
Eigenvalue 10 : 1.8505398128271504
Eigenvalue 11 : 1.5549581320873724
Eigenvalue 12 : 1.2693179512672117
Eigenvalue 13 : 1.0000000000000044
Eigenvalue 14 : 0.7530203962825326
Eigenvalue 15 : 0.5338962563403483
Eigenvalue 16 : 0.34752245136800985
Eigenvalue 17 : 0.19806226419516174
Eigenvalue 18 : 0.08885438842771881
Eigenvalue 19 : 0.022338347549742853


Singular values are  square root of eigenvalues of A_T*A

In [ ]:
np.linalg.eigvals(svd) # finding the eigenvalues of A_T * A

array([1.58217922e+01, 1.52970600e+01, 1.44547305e+01, 1.33405922e+01,
       1.20138752e+01, 1.05428765e+01, 9.00000000e+00, 7.45662445e+00,
       5.97822974e+00, 4.62017910e+00, 3.42449760e+00, 2.41789479e+00,
       1.61116806e+00, 1.00000000e+00, 5.67039717e-01, 2.85045213e-01,
       1.20771854e-01, 3.92286605e-02, 7.89510234e-03, 4.99001771e-04])

In [ ]:
np.sqrt(np.linalg.eigvals(svd)) # finding the singular values of A or S matrix already show singular values of A

array([3.97766165, 3.91114561, 3.80193774, 3.65247755, 3.46610374,
       3.2469796 , 3.        , 2.73068205, 2.44504187, 2.14946019,
       1.85053981, 1.55495813, 1.26931795, 1.        , 0.7530204 ,
       0.53389626, 0.34752245, 0.19806226, 0.08885439, 0.02233835])