In [5]:
import numpy as np
from scipy.sparse import diags


In [1]:
def LU_Decomposition(A):
    
    #Get the number of rows
    n = A.shape[0]
    
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
        
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return L, U
    print(L,U)

At the below code, we use forward substitution 
L*U*x = b where U*x = y means that L*y = b

In [2]:
def forward_substitution(L, b):
    
    n = L.shape[0] # number of rows

    y = np.zeros_like(b, dtype=np.double); # solution vector

    y[0] = b[0] / L[0, 0]  # Before forward-substitution, first thing is to initialize 
    
    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]
        
    return y

In [3]:
def backward_substitution(U, y):

    n = U.shape[0]  # Number of rows
    
    x = np.zeros_like(y, dtype=np.double); # solution vector

    x[-1] = y[-1] / U[-1, -1] # Before backward-substitution, first thing is to initialize
    
    
    for i in range(n-2, -1, -1): # we have to start last row since we do backward substitution
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]
        
    return x

Implementation

In [9]:
A = diags([1, 2, 3], [-1, 0, 1], shape=(20, 20)).toarray()
A

array([[2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [7]:
b = np.ones(20)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [10]:
LU_Decomposition(A)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.5       ,  1.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  2.        ,  1.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        , -0.25      ,  1.        ,  0.        ,
          0.        ,  0.        , 

In [11]:
L , U = LU_Decomposition(A)

In [12]:
y = forward_substitution(L, b)
y

array([ 1.        ,  0.5       ,  0.        ,  1.        ,  0.63636364,
        0.3       ,  1.23076923,  0.71428571,  0.45205479,  2.5       ,
        0.79087452,  0.54782609, -0.92366412,  0.89177102,  0.62076835,
        0.14285714,  1.06668301,  0.68630137,  0.38598981,  1.56431535])

In [13]:
x = backward_substitution(U, y)
x

array([-8.58156268e+03,  5.72137512e+03, -9.53395853e+02, -1.27119447e+03,
        1.16559493e+03, -3.52998464e+02, -1.52866001e+02,  2.19910156e+02,
       -9.53181033e+01, -9.42464964e+00,  3.83891342e+01, -2.21178729e+01,
        2.28220388e+00,  6.18448839e+00, -4.55039355e+00,  1.30543290e+00,
        9.79842580e-01, -7.55039355e-01,  5.10078710e-01,  2.44960645e-01])