In [5]:
import numpy as np
from scipy.linalg import toeplitz

In [6]:
A=toeplitz([2,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

In [7]:
x0=[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
b=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0]

## Steepest Descent

In [8]:
def steepest_descent(A, b, x0, tol=1e-6, max_iter=100):

    x = x0.copy()
    r = b - A.dot(x)

    for i in range(max_iter):
        Ar = A.dot(r)
        # Calculate the step size alpha
        alpha = np.sqrt(r.dot(r)) / r.dot(Ar)
         # Update the solution vector x
        x += alpha * r
        
        # Check if the residual is below the convergence threshold
        if np.sqrt(r.dot(r)) < tol:
            break
        # Update the search direction r    
        r -= alpha * Ar
        
    return x

In [9]:
steepest_descent(A, b, x0, tol=1e-6, max_iter=100)

array([ 7.24286166, 14.37507619, 21.3594872 , 27.9824819 , 34.23052479,
       40.07167649, 45.1518751 , 49.76793398, 53.33421219, 56.27584439,
       58.07281341, 58.74456718, 58.44840958, 56.56046452, 53.60165294,
       48.87309243, 42.71364546, 34.88959056, 25.10785755, 13.59392378])

## Conjugate Gradient

In [10]:

def conjugate_gradient(A, b, x0, tol=1e-6, max_iter=100):


  # Set the initial residual and search direction
    r = b - np.dot(A, x0)
    p = r

    for i in range(max_iter):
    # Calculate the step size alpha
        alpha = np.dot(r, r) / np.dot(p, np.dot(A, p))
    # Update the solution vector x
        x0 = x0 + alpha * p
    # Update the residual vector r
        r_prev = r
        r = b - np.dot(A, x0)
    # Check if the residual is below the convergence threshold
        if np.linalg.norm(r) < tol:
            break
    # Calculate beta using the Hestenes-Stiefel method
        beta = np.dot(r, r) / np.dot(r_prev, r_prev)
    # Update the search direction p
        p = r + beta * p

        return(x0)

In [11]:
conjugate_gradient(A, b, x0, tol=1e-6, max_iter=100)

array([-4.9625,  2.325 ,  2.9875,  3.65  ,  4.3125,  4.975 ,  5.6375,
        6.3   ,  6.9625,  7.625 ,  8.2875,  8.95  ,  9.6125, 10.275 ,
       10.9375, 11.6   , 12.2625, 12.925 , 13.5875,  7.625 ])

In [12]:
np.linalg.solve(A, b)

array([ 7.33333333, 14.56666667, 21.6       , 28.33333333, 34.66666667,
       40.5       , 45.73333333, 50.26666667, 54.        , 56.83333333,
       58.66666667, 59.4       , 58.93333333, 57.16666667, 54.        ,
       49.33333333, 43.06666667, 35.1       , 25.33333333, 13.66666667])


Note that these methos assume that the matrix A is symmetric and positive definite, which is a requirement to converge. If the matrix A is not symmetric and positive definite, methods may not converge or may converge to a non-optimal solution.

In [13]:
from numpy import linalg as LA

def is_pos_def(A):
    """check if a matrix is symmetric positive definite"""
    return np.all(np.linalg.eigvals(A) > 0)

In [14]:
is_pos_def(A)

True

Note that these methods assume that the matrix A is symmetric and positive definite, which is a
requirement to converge. If the matrix A is not symmetric and positive definite, methods may not
converge or may converge to a non-optimal solution.

In [36]:
%%time
conjugate_gradient(A, b, x0, tol=1e-6, max_iter=100)

CPU times: user 1.05 ms, sys: 0 ns, total: 1.05 ms
Wall time: 1.06 ms


array([ 7.33333333, 14.56666667, 21.6       , 28.33333333, 34.66666667,
       40.5       , 45.73333333, 50.26666667, 54.        , 56.83333333,
       58.66666667, 59.4       , 58.93333333, 57.16666667, 54.        ,
       49.33333333, 43.06666667, 35.1       , 25.33333333, 13.66666667])

In [37]:
%%time
steepest_descent(A, b, x0, tol=1e-6, max_iter=100)

CPU times: user 2.49 ms, sys: 0 ns, total: 2.49 ms
Wall time: 2.67 ms


array([ 8.34654432, 17.35080654, 24.88373093, 33.13149786, 40.4143787 ,
       46.64309863, 53.34235316, 57.58126325, 62.30889354, 65.06857406,
       66.76757378, 67.73360092, 66.37753513, 64.54347088, 60.35827484,
       55.0130042 , 47.72378378, 38.6934217 , 27.77265083, 14.90418828])

As we see from above time results, Conjugate Gradient Method is faster than Steepest Descent Method